INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (1,'Primero. Biologia y Geologia',1),
	 (2,'Primero. Geografia e Historia ',1),
	 (3,'Primero. Lengua Castellana y Literatura ',1),
	 (4,'Primero. Matematicas ',1),
	 (5,'Primero. Primera Lengua Extranjera ',1),
	 (6,'Primero. Educacion Fisica ',1),
	 (7,'Primero. Educacion Plastica, Visual y Audiovisual ',1),
	 (8,'Primero. Musica ',1),
	 (9,'Primero. Religion',1),
	 (10,'Primero. Valores Eticos',1);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (11,'Primero. Segunda Lengua Extranjera',1),
	 (12,'Primero. Biologia y Geologia',2),
	 (13,'Primero. Geografia e Historia ',2),
	 (14,'Primero. Lengua Castellana y Literatura ',2),
	 (15,'Primero. Matematicas ',2),
	 (16,'Primero. Primera Lengua Extranjera ',2),
	 (17,'Primero. Educacion Fisica ',2),
	 (18,'Primero. Educacion Plastica, Visual y Audiovisual ',2),
	 (19,'Primero. Musica ',2),
	 (20,'Primero. Religion',2);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (21,'Primero. Valores Eticos',2),
	 (22,'Primero. Segunda Lengua Extranjera',2),
	 (23,'Primero. Biologia y Geologia',3),
	 (24,'Primero. Geografia e Historia ',3),
	 (25,'Primero. Lengua Castellana y Literatura ',3),
	 (26,'Primero. Matematicas ',3),
	 (27,'Primero. Primera Lengua Extranjera ',3),
	 (28,'Primero. Educacion Fisica ',3),
	 (29,'Primero. Educacion Plastica, Visual y Audiovisual ',3),
	 (30,'Primero. Musica ',3);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (31,'Primero. Religion',3),
	 (32,'Primero. Valores Eticos',3),
	 (33,'Primero. Segunda Lengua Extranjera',3),
	 (34,'Primero. Biologia y Geologia',4),
	 (35,'Primero. Geografia e Historia ',4),
	 (36,'Primero. Lengua Castellana y Literatura ',4),
	 (37,'Primero. Matematicas ',4),
	 (38,'Primero. Primera Lengua Extranjera ',4),
	 (39,'Primero. Educacion Fisica ',4),
	 (40,'Primero. Educacion Plastica, Visual y Audiovisual ',4);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (41,'Primero. Musica ',4),
	 (42,'Primero. Religion',4),
	 (43,'Primero. Valores Eticos',4),
	 (44,'Primero. Segunda Lengua Extranjera',4),
	 (45,'Segundo. Biologia y Geologia',5),
	 (46,'Segundo. Geografia e Historia ',5),
	 (47,'Segundo. Lengua Castellana y Literatura ',5),
	 (48,'Segundo. Matematicas ',5),
	 (49,'Segundo. Primera Lengua Extranjera ',5),
	 (50,'Segundo. Educacion Fisica ',5);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (51,'Segundo. Educacion Plastica, Visual y Audiovisual ',5),
	 (52,'Segundo. Musica ',5),
	 (53,'Segundo. Religion',5),
	 (54,'Segundo. Valores Eticos',5),
	 (55,'Segundo. Segunda Lengua Extranjera',5),
	 (56,'Segundo. Fisica y Quimica',5),
	 (57,'Segundo. Biologia y Geologia',6),
	 (58,'Segundo. Geografia e Historia ',6),
	 (59,'Segundo. Lengua Castellana y Literatura ',6),
	 (60,'Segundo. Matematicas ',6);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (61,'Segundo. Primera Lengua Extranjera ',6),
	 (62,'Segundo. Educacion Fisica ',6),
	 (63,'Segundo. Educacion Plastica, Visual y Audiovisual ',6),
	 (64,'Segundo. Musica ',6),
	 (65,'Segundo. Religion',6),
	 (66,'Segundo. Valores Eticos',6),
	 (67,'Segundo. Segunda Lengua Extranjera',6),
	 (68,'Segundo. Fisica y Quimica',6),
	 (69,'Segundo. Biologia y Geologia',7),
	 (70,'Segundo. Geografia e Historia ',7);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (71,'Segundo. Lengua Castellana y Literatura ',7),
	 (72,'Segundo. Matematicas ',7),
	 (73,'Segundo. Primera Lengua Extranjera ',7),
	 (74,'Segundo. Educacion Fisica ',7),
	 (75,'Segundo. Educacion Plastica, Visual y Audiovisual ',7),
	 (76,'Segundo. Musica ',7),
	 (77,'Segundo. Religion',7),
	 (78,'Segundo. Valores Eticos',7),
	 (79,'Segundo. Segunda Lengua Extranjera',7),
	 (80,'Segundo. Fisica y Quimica',7);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (81,'Segundo. Biologia y Geologia',8),
	 (82,'Segundo. Geografia e Historia ',8),
	 (83,'Segundo. Lengua Castellana y Literatura ',8),
	 (84,'Segundo. Matematicas ',8),
	 (85,'Segundo. Primera Lengua Extranjera ',8),
	 (86,'Segundo. Educacion Fisica ',8),
	 (87,'Segundo. Educacion Plastica, Visual y Audiovisual ',8),
	 (88,'Segundo. Musica ',8),
	 (89,'Segundo. Religion',8),
	 (90,'Segundo. Valores Eticos',8);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (91,'Segundo. Segunda Lengua Extranjera',8),
	 (92,'Segundo. Fisica y Quimica',8),
	 (93,'Tercero. Biologia y Geologia',9),
	 (94,'Tercero. Geografia e Historia ',9),
	 (95,'Tercero. Lengua Castellana y Literatura ',9),
	 (96,'Tercero. Matematicas Orientadas a las Ensenianzas Academicas',9),
	 (97,'Tercero. Matematicas Aplicadas',9),
	 (98,'Tercero. Primera Lengua Extranjera ',9),
	 (99,'Tercero. Educacion Fisica ',9),
	 (100,'Tercero. Educacion Plastica, Visual y Audiovisual ',9);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (101,'Tercero. Musica ',9),
	 (102,'Tercero. Religion',9),
	 (103,'Tercero. Valores Eticos',9),
	 (104,'Tercero. Segunda Lengua Extranjera',9),
	 (105,'Tercero. Fisica y Quimica',9),
	 (106,'Tercero. Educacion para la Ciudadania y DDHH',9),
	 (107,'Tercero. Tecnologia',9),
	 (108,'Tercero. Biologia y Geologia',10),
	 (109,'Tercero. Geografia e Historia ',10),
	 (110,'Tercero. Lengua Castellana y Literatura ',10);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (111,'Tercero. Matematicas Orientadas a las Ensenianzas Academicas',10),
	 (112,'Tercero. Matematicas Aplicadas',10),
	 (113,'Tercero. Primera Lengua Extranjera ',10),
	 (114,'Tercero. Educacion Fisica ',10),
	 (115,'Tercero. Educacion Plastica, Visual y Audiovisual ',10),
	 (116,'Tercero. Musica ',10),
	 (117,'Tercero. Religion',10),
	 (118,'Tercero. Valores Eticos',10),
	 (119,'Tercero. Segunda Lengua Extranjera',10),
	 (120,'Tercero. Fisica y Quimica',10);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (121,'Tercero. Educacion para la Ciudadania y DDHH',10),
	 (122,'Tercero. Tecnologia',10),
	 (123,'Tercero. Biologia y Geologia',11),
	 (124,'Tercero. Geografia e Historia ',11),
	 (125,'Tercero. Lengua Castellana y Literatura ',11),
	 (126,'Tercero. Matematicas Orientadas a las Ensenianzas Academicas',11),
	 (127,'Tercero. Matematicas Aplicadas',11),
	 (128,'Tercero. Primera Lengua Extranjera ',11),
	 (129,'Tercero. Educacion Fisica ',11),
	 (130,'Tercero. Educacion Plastica, Visual y Audiovisual ',11);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (131,'Tercero. Musica ',11),
	 (132,'Tercero. Religion',11),
	 (133,'Tercero. Valores Eticos',11),
	 (134,'Tercero. Segunda Lengua Extranjera',11),
	 (135,'Tercero. Fisica y Quimica',11),
	 (136,'Tercero. Educacion para la Ciudadania y DDHH',11),
	 (137,'Tercero. Tecnologia',11),
	 (138,'Tercero. Biologia y Geologia',12),
	 (139,'Tercero. Geografia e Historia ',12),
	 (140,'Tercero. Lengua Castellana y Literatura ',12);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (141,'Tercero. Matematicas Orientadas a las Ensenianzas Academicas',12),
	 (142,'Tercero. Matematicas Aplicadas',12),
	 (143,'Tercero. Primera Lengua Extranjera ',12),
	 (144,'Tercero. Educacion Fisica ',12),
	 (145,'Tercero. Educacion Plastica, Visual y Audiovisual ',12),
	 (146,'Tercero. Musica ',12),
	 (147,'Tercero. Religion',12),
	 (148,'Tercero. Valores Eticos',12),
	 (149,'Tercero. Segunda Lengua Extranjera',12),
	 (150,'Tercero. Fisica y Quimica',12);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (151,'Tercero. Educacion para la Ciudadania y DDHH',12),
	 (152,'Tercero. Tecnologia',12),
	 (153,'Cuarto. Geografia e Historia',13),
	 (154,'Cuarto. Lengua Castellana y Literatura',13),
	 (155,'Cuarto. Matematicas Academicas',13),
	 (156,'Cuarto. Segunda Lengua Extranjera',13),
	 (157,'Cuarto. Primera Lengua Extranjera',13),
	 (158,'Cuarto. Biologia y Geologia',13),
	 (159,'Cuarto. Fisica y Quimica',13),
	 (160,'Cuarto. Tecnologia',13);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (161,'Cuarto. Educacion Fisica',13),
	 (162,'Cuarto. Religion',13),
	 (163,'Cuarto. Valores Eticos',13),
	 (164,'Cuarto. Geografia e Historia',14),
	 (165,'Cuarto. Lengua Castellana y Literatura',14),
	 (166,'Cuarto. Matematicas Academicas',14),
	 (167,'Cuarto. Segunda Lengua Extranjera',14),
	 (168,'Cuarto. Primera Lengua Extranjera',14),
	 (169,'Cuarto. Biologia y Geologia',14),
	 (170,'Cuarto. Fisica y Quimica',14);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (171,'Cuarto. Tecnologia',14),
	 (172,'Cuarto. Educacion Fisica',14),
	 (173,'Cuarto. Religion',14),
	 (174,'Cuarto. Valores Eticos',14),
	 (175,'Cuarto. Geografia e Historia',15),
	 (176,'Cuarto. Lengua Castellana y Literatura',15),
	 (177,'Cuarto. Matematicas Academicas',15),
	 (178,'Cuarto. Segunda Lengua Extranjera',15),
	 (179,'Cuarto. Primera Lengua Extranjera',15),
	 (180,'Cuarto. Biologia y Geologia',15);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (181,'Cuarto. Fisica y Quimica',15),
	 (182,'Cuarto. Tecnologia',15),
	 (183,'Cuarto. Educacion Fisica',15),
	 (184,'Cuarto. Religion',15),
	 (185,'Cuarto. Valores Eticos',15),
	 (186,'Cuarto. Geografia e Historia',16),
	 (187,'Cuarto. Lengua Castellana y Literatura',16),
	 (188,'Cuarto. Matematicas Academicas',16),
	 (189,'Cuarto. Segunda Lengua Extranjera',16),
	 (190,'Cuarto. Primera Lengua Extranjera',16);
INSERT INTO instituto.asignatura (Codigo,Nombre,GRUPO_Codigo) VALUES
	 (191,'Cuarto. Biologia y Geologia',16),
	 (192,'Cuarto. Fisica y Quimica',16),
	 (193,'Cuarto. Tecnologia',16),
	 (194,'Cuarto. Educacion Fisica',16),
	 (195,'Cuarto. Religion',16),
	 (196,'Cuarto. Valores Eticos',16);
